import type { ChainKey, SectorKey } from "@/lib/mock-data";

export type AssetMetadata = {
  name: string;
  chain: ChainKey;
  sectors: SectorKey[];
};

const metadataBySymbol: Record<string, AssetMetadata> = {
  BTC: { name: "Bitcoin", chain: "BTC", sectors: ["Layer 1"] },
  ETH: { name: "Ethereum", chain: "ETH", sectors: ["Layer 1", "Infra"] },
  BNB: { name: "BNB", chain: "BSC", sectors: ["Layer 1", "CEX"] },
  SOL: { name: "Solana", chain: "SOL", sectors: ["Layer 1"] },
  XRP: { name: "XRP", chain: "XRP", sectors: ["Layer 1"] },
  ADA: { name: "Cardano", chain: "ADA", sectors: ["Layer 1"] },
  DOGE: { name: "Dogecoin", chain: "DOGE", sectors: ["Meme"] },
  ZEC: { name: "Zcash", chain: "ZEC", sectors: ["Layer 1"] },
  DASH: { name: "Dash", chain: "DASH", sectors: ["Layer 1"] },
  ALGO: { name: "Algorand", chain: "ALGO", sectors: ["Layer 1"] },
  TIA: { name: "Celestia", chain: "TIA", sectors: ["Infra"] },
  RONIN: { name: "Ronin", chain: "RONIN", sectors: ["Infra"] },
  DYDX: { name: "dYdX", chain: "DYDX", sectors: ["DeFi", "Perps"] },
  IOTA: { name: "IOTA", chain: "IOTA", sectors: ["Infra"] },
  ETC: { name: "Ethereum Classic", chain: "ETC", sectors: ["Layer 1"] },
  ZEN: { name: "Horizen", chain: "ZEN", sectors: ["Infra"] },
  TRX: { name: "TRON", chain: "TRX", sectors: ["Layer 1"] },
  AVAX: { name: "Avalanche", chain: "AVAX", sectors: ["Layer 1"] },
  LINK: { name: "Chainlink", chain: "ETH", sectors: ["Infra"] },
  XLM: { name: "Stellar", chain: "XRP", sectors: ["Layer 1"] },
  SUI: { name: "Sui", chain: "SUI", sectors: ["Layer 1"] },
  LTC: { name: "Litecoin", chain: "LTC", sectors: ["Layer 1"] },
  BCH: { name: "Bitcoin Cash", chain: "BCH", sectors: ["Layer 1"] },
  DOT: { name: "Polkadot", chain: "DOT", sectors: ["Infra"] },
  NEAR: { name: "NEAR Protocol", chain: "NEAR", sectors: ["Layer 1", "AI"] },
  TON: { name: "Toncoin", chain: "TON", sectors: ["Layer 1"] },
  UNI: { name: "Uniswap", chain: "ETH", sectors: ["DeFi", "DEX"] },
  AAVE: { name: "Aave", chain: "ETH", sectors: ["DeFi", "Yield"] },
  ENA: { name: "Ethena", chain: "ETH", sectors: ["DeFi", "Yield"] },
  PENDLE: { name: "Pendle", chain: "ETH", sectors: ["DeFi", "Yield"] },
  CRV: { name: "Curve DAO", chain: "ETH", sectors: ["DeFi", "DEX"] },
  COMP: { name: "Compound", chain: "ETH", sectors: ["DeFi", "Yield"] },
  MKR: { name: "Maker", chain: "ETH", sectors: ["DeFi"] },
  LDO: { name: "Lido DAO", chain: "ETH", sectors: ["DeFi", "Yield"] },
  RUNE: { name: "THORChain", chain: "Unclassified", sectors: ["DeFi", "DEX"] },
  CAKE: { name: "PancakeSwap", chain: "BSC", sectors: ["DeFi", "DEX"] },
  JUP: { name: "Jupiter", chain: "SOL", sectors: ["DeFi", "DEX"] },
  RAY: { name: "Raydium", chain: "SOL", sectors: ["DeFi", "DEX"] },
  JTO: { name: "Jito", chain: "SOL", sectors: ["DeFi", "Yield"] },
  ORCA: { name: "Orca", chain: "SOL", sectors: ["DeFi", "DEX"] },
  PYTH: { name: "Pyth Network", chain: "SOL", sectors: ["Infra"] },
  WIF: { name: "dogwifhat", chain: "SOL", sectors: ["Meme"] },
  BONK: { name: "Bonk", chain: "SOL", sectors: ["Meme"] },
  PNUT: { name: "Peanut the Squirrel", chain: "SOL", sectors: ["Meme"] },
  POPCAT: { name: "Popcat", chain: "SOL", sectors: ["Meme"] },
  MEW: { name: "cat in a dogs world", chain: "SOL", sectors: ["Meme"] },
  FARTCOIN: { name: "Fartcoin", chain: "SOL", sectors: ["Meme"] },
  PUMP: { name: "Pump.fun", chain: "SOL", sectors: ["Meme"] },
  OP: { name: "Optimism", chain: "BASE", sectors: ["Infra"] },
  ARB: { name: "Arbitrum", chain: "ARB", sectors: ["Infra"] },
  STRK: { name: "Starknet", chain: "ETH", sectors: ["Infra"] },
  MANTA: { name: "Manta Network", chain: "ETH", sectors: ["Infra"] },
  ZK: { name: "ZKsync", chain: "ETH", sectors: ["Infra"] },
  ZRO: { name: "LayerZero", chain: "ETH", sectors: ["Infra"] },
  WLD: { name: "Worldcoin", chain: "ETH", sectors: ["AI"] },
  FET: { name: "Artificial Superintelligence", chain: "ETH", sectors: ["AI"] },
  TAO: { name: "Bittensor", chain: "ETH", sectors: ["AI"] },
  RENDER: { name: "Render", chain: "ETH", sectors: ["AI"] },
  GRT: { name: "The Graph", chain: "ETH", sectors: ["AI", "Infra"] },
  VIRTUAL: { name: "Virtuals Protocol", chain: "BASE", sectors: ["AI"] },
  AERO: { name: "Aerodrome", chain: "BASE", sectors: ["DeFi", "DEX"] },
  AIXBT: { name: "aixbt", chain: "BASE", sectors: ["AI"] },
  BRETT: { name: "Brett", chain: "BASE", sectors: ["Meme"] },
  ZORA: { name: "Zora", chain: "BASE", sectors: ["Infra"] },
  GMX: { name: "GMX", chain: "ARB", sectors: ["DeFi", "Perps"] },
  JOE: { name: "Trader Joe", chain: "AVAX", sectors: ["DeFi", "DEX"] },
  GM: { name: "GM", chain: "AVAX", sectors: ["Meme"] },
  MATIC: { name: "Polygon", chain: "MATIC", sectors: ["Infra"] },
  POL: { name: "Polygon Ecosystem Token", chain: "MATIC", sectors: ["Infra"] },
  OKB: { name: "OKB", chain: "ETH", sectors: ["CEX"] },
  GT: { name: "GateToken", chain: "ETH", sectors: ["CEX"] },
  KCS: { name: "KuCoin Token", chain: "ETH", sectors: ["CEX"] },
  CRO: { name: "Cronos", chain: "Unclassified", sectors: ["CEX", "Layer 1"] },
  PEPE: { name: "Pepe", chain: "ETH", sectors: ["Meme"] },
  SHIB: { name: "Shiba Inu", chain: "ETH", sectors: ["Meme"] },
  FLOKI: { name: "Floki", chain: "ETH", sectors: ["Meme"] },
  MEME: { name: "Memecoin", chain: "ETH", sectors: ["Meme"] },
  MOG: { name: "Mog Coin", chain: "ETH", sectors: ["Meme"] },
  TURBO: { name: "Turbo", chain: "ETH", sectors: ["Meme"] },
  PENGU: { name: "Pudgy Penguins", chain: "SOL", sectors: ["Meme"] },
  ICP: { name: "Internet Computer", chain: "ICP", sectors: ["Layer 1", "Infra"] },
  ATOM: { name: "Cosmos", chain: "ATOM", sectors: ["Layer 1", "Infra"] },
  INJ: { name: "Injective", chain: "INJ", sectors: ["Layer 1", "DeFi"] },
  SEI: { name: "Sei", chain: "SEI", sectors: ["Layer 1", "DeFi"] },
  APT: { name: "Aptos", chain: "APT", sectors: ["Layer 1"] },
  HBAR: { name: "Hedera", chain: "HBAR", sectors: ["Layer 1", "Infra"] },
  FIL: { name: "Filecoin", chain: "FIL", sectors: ["Infra"] },
  AR: { name: "Arweave", chain: "AR", sectors: ["Infra"] },
  IMX: { name: "Immutable", chain: "ETH", sectors: ["Infra"] },
  SAND: { name: "The Sandbox", chain: "ETH", sectors: ["Meme"] },
  MANA: { name: "Decentraland", chain: "ETH", sectors: ["Meme"] },
  AXS: { name: "Axie Infinity", chain: "ETH", sectors: ["Meme"] },
  GALA: { name: "Gala", chain: "ETH", sectors: ["Meme"] }
};

export function resolveAssetMetadata(symbol: string): AssetMetadata {
  return metadataBySymbol[symbol.toUpperCase()] || {
    name: symbol.toUpperCase(),
    chain: "Unclassified",
    sectors: ["Unclassified"]
  };
}
